### ISSUE TITLE
请问一下warehouse_name应该怎么命名

### ISSUE THREAD

**Issue by liuxingbo12138** [OSVAI/KernelWarehouse#3]
![image](https://github.com/OSVAI/KernelWarehouse/assets/79137028/a8dbc23e-0e6b-4f11-8a46-6132c332daa7)
![image](https://github.com/OSVAI/KernelWarehouse/assets/79137028/547cd335-b048-46ba-8a67-81034a147ec3)
我想计算下KWConv不同Warehouse_Manager_Ratio下的卷积参数和速度，但是我不是太懂怎么设置warehouse_name参数

**Comment by AEYCstark** [comment]
你好。问一下你这个类是哪来的呀？自己写的吗
